# Configuration file for pre-commit
---
repos:
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 1.5.3
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3.10
