[project]
name = "seabirdscientific"
version = "3.0.0a20"
description = "Sea-Bird Scientific Community Toolkit"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    {name = "Sea-Bird Scientific", email = "techsupport@seabird.com"},
    {name = "Ryan Anderson", email = "randerson@seabird.com"},
    {name = "Lukas Christensen", email = "lchristensen@seabird.com"},
    {name = "Dane Lucas", email = "dlucas@seabird.com"},
    {name = "Eric Rehm", email = "erehm@seabird.com"},
    {name = "Bruce Rhoades", email = "brhoades@seabird.com"},
    {name = "Jesse Templin", email = "jtemplin@seabird.com"},
]
requires-python = ">=3.11"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "gsw ~= 3.6",
  "line-profiler ~= 5.0",
  "matplotlib ~= 3.11",
  "numpy ~= 2.4",
  "pandas ~= 3.0",
  "plotly ~= 6.9",
  "scipy ~= 1.17",
  "xarray ~= 2026.7",
]

[project.optional-dependencies]
notebooks = [
  "ipykernel ~= 7.3",
  "nbformat ~= 5.10",
]

docs = [
  "sbsfuro ~= 0.1",
  "sphinx ~= 9.0",
  "sphinx-mdinclude ~= 0.6",
]

[dependency-groups]
dev = [
  "ipykernel ~= 7.3",
  "kaleido ~= 1.3",
  "nbconvert[webpdf] ~= 7.17",
  "nbformat ~= 5.10",
  "notebook ~= 7.6",
  "ruff ~= 0.16",
  "pytest ~= 9.1",
  "pytest-cov ~= 7.1",
]

[project.urls]
Homepage = "https://www.seabird.com/software"
Repository = "https://github.com/Sea-BirdScientific/seabirdscientific"

[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools>=61",
]

[tool.setuptools.package-data]
seabirdscientific = ["resources/**"]

[tool.ty.src]
include = [
  "src",
  "tests",
]
exclude = [
  "tests/resources",
]

[tool.ruff]
line-length=99
extend-exclude = [
  ".github",
]
src = [
  "src",
  "tests"
]

[tool.ruff.lint]
ignore = ["DTZ"]

[tool.pytest.ini_options]
testpaths = [
  "tests"
]
norecursedirs = [
  "__pycache__",
  "resources",
  "results",
]

