name: Black Formatter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  black:
    name: Run Black
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      # 4. Run Black in check mode
      - name: Check code formatting
        run: |
          black --check .
