name: Publish Docs

on:
  push:
    branches:
      - main
      - tkit-156-migration-guide2

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install sbsfuro
      - run: pip install sphinx
      - run: pip install sphinx-mdinclude

      - run: sphinx-build -b html -a -E docs/source _build/html

      - uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - uses: actions/deploy-pages@v4