name: Pytest

on:
  pull_request:
    branches: ["**"]

concurrency:
  group: pytest-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    name: Run Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync

      - name: Run pytest
        run: uv run pytest
