name: Ruff Linter

on:
  pull_request:
    branches: ["**"]

concurrency:
  group: ruff-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    name: Run Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync

      - name: Run ruff check and ruff format
        run: |
          uv run ruff check . --ignore I001
          uv run ruff format --check .